syntax = "proto3";

option csharp_namespace = "SappGRPC";

import "google/protobuf/wrappers.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

package Sapp;

service WeatherForecastService {
    rpc GetWeatherForecast (google.protobuf.Empty) returns (GetWeatherForecastResponse);
}

message GetWeatherForecastResponse {
  repeated WeatherForecast weatherForecasts = 1;
}

message WeatherForecast {
  google.protobuf.Timestamp date = 1;
  sint32 temperatureC = 2;
  sint32 temperatureF = 3;
  google.protobuf.StringValue summary = 4;
}
